---
language: python
services: docker

sudo: false

install:
  - pip install ansible molecule docker testinfra
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - molecule create
  - molecule converge
  - molecule verify

notifications:
  slack:
    secure: tAp+nFtYVGNmM3FZ2GqNKLIe8Xb/suLr8s20vrt7uNwYLkBY1kHzb76YmisgAhaV42Shjm00PDddk67NPN01ZkgRC2SF/ldzkASuG+vUwDSGiXzkrgq0IPk8DZ/BLmbublJl40j+U542AVkajQJ+SuFpACNlLFPU0rsuTR1ioCXmUcOrcOrp92q8xdG8L/CBPe3j+VHZEpXjC3wSiEXwIhK/YKrMvBoHnjnt95RXipQOEyN5iQSxvAdtOR2AA5aVtklmkCeHFWZsvb7dLqJJ/ekuGjbBwaIuczuyGcG0IMnXhurcMHMLJ1NHqVM39MnLkU9zjmV7wymsXT+DNqR+VhJ3ctDbZY3LazH+XxkZbUcmQX3Lr7LzlBhjTxH4aweBS6HCJrYRRBHkw+ZR0gB7ACJkare+QJw/Sihury96dV8OErCH5PgpGvkrk1XeP7CMvPoYRyrt+OMEZjsgAlBrxM6iQDHZ9rUl4YKaDMipHX5ml6R3g5La+5R0S941orZdF67al48aberFhcMnErzkVzfANa8XXzR/R8Uus0VT+O1iSOudWBLmqjfrrM5uGsclhtz8qB/Y2R5dvzmsB53y5gVvCSebcAQLOyY8kILDwRyDBZU2ih+RzTMenOEJdiAvqtWoHYeWFJql59RcbQVV4/+0Mm0st3axl5wEmBug4W8=
