---
dependency:
  name: galaxy
driver:
  name: docker
  # name: vagrant
  # provider:
  #   name: libvirt
lint: | 
  yamllint
  ansible-lint
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu1604-ansible"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
    # box: ubuntu/xenial64
    # memory: 512
    # cpus: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ./tests
