---
dependency:
  name: galaxy
driver:
  name: docker
  # name: vagrant
  # provider:
  #   name: libvirt
lint:
  name: yamllint
platforms:
  - name: instance
    image: "ubuntu:16.04"
    pre_build_image: True
    # box: ubuntu/xenial64
    # memory: 512
    # cpus: 1
provisioner:
  name: ansible
lint: ansible-lint
verifier:
  name: testinfra
  additional_files_or_dirs:
    - ./tests
